teams = {
    "ANA": {
        "name": "ducks",
        "handle": "@AnaheimDucks",
        "hashtag": "#LetsGoDucks",
        "abbreviation": "ANA",
    },
    "ARI": {
        "name": "coyotes",
        "handle": "@ArizonaCoyotes",
        "hashtag": "#Yotes",
        "abbreviation": "ARI",
    },
    "BOS": {
        "name": "bruins",
        "handle": "@NHLBruins",
        "hashtag": "#NHLBruins",
        "abbreviation": "BOS",
    },
    "BUF": {
        "name": "sabres",
        "handle": "@BuffaloSabres",
        "hashtag": "#Sabres",
        "abbreviation": "BUF",
    },
    "CGY": {
        "name": "flames",
        "handle": "@NHLFlames",
        "hashtag": "#CofRed",
        "abbreviation": "CGY",
    },
    "CAR": {
        "name": "hurricanes",
        "handle": "@NHLCanes",
        "hashtag": "#Redvolution",
        "abbreviation": "CAR",
    },
    "CHI": {
        "name": "blackhawks",
        "handle": "@NHLBlackhawks",
        "hashtag": "#Blackhawks",
        "abbreviation": "CHI",
    },
    "COL": {
        "name": "avalanche",
        "handle": "@Avalanche",
        "hashtag": "#GoAvsGo",
        "abbreviation": "COL",
    },
    "CBJ": {
        "name": "bluejackets",
        "handle": "@BlueJacketsNHL",
        "hashtag": "#CBJ",
        "abbreviation": "CBJ",
    },
    "DAL": {
        "name": "stars",
        "handle": "@DallasStars",
        "hashtag": "#GoStars",
        "abbreviation": "DAL",
    },
    "DET": {
        "name": "redwings",
        "handle": "@DetroitRedWings",
        "hashtag": "#LGRW",
        "abbreviation": "DET",
    },
    "EDM": {
        "name": "oilers",
        "handle": "@EdmontonOilers",
        "hashtag": "#LetsgoOilers",
        "abbreviation": "EDM",
    },
    "FLA": {
        "name": "panthers",
        "handle": "@FlaPanthers",
        "hashtag": "#FlaPanthers",
        "abbreviation": "FLA",
    },
    "LAK": {
        "name": "kings",
        "handle": "@LAKings",
        "hashtag": "#GoKingsGo",
        "abbreviation": "LAK",
    },
    "MIN": {
        "name": "wild",
        "handle": "@mnwild",
        "hashtag": "#mnwild",
        "abbreviation": "MIN",
    },
    "MTL": {
        "name": "canadiens",
        "handle": "@CanadiensMTL",
        "hashtag": "#GoHabsGo",
        "abbreviation": "MTL",
    },
    "NSH": {
        "name": "predators",
        "handle": "@PredsNHL",
        "hashtag": "#Preds",
        "abbreviation": "NSH",
    },
    "NJD": {
        "name": "devils",
        "handle": "@NJDevils",
        "hashtag": "#NJDevils",
        "abbreviation": "NJD",
    },
    "NYI": {
        "name": "islanders",
        "handle": "@NYIslanders",
        "hashtag": "#Isles",
        "abbreviation": "NYI",
    },
    "NYR": {
        "name": "rangers",
        "handle": "@NYRangers",
        "hashtag": "#NYR",
        "abbreviation": "NYR",
    },
    "OTT": {
        "name": "senators",
        "handle": "@Senators",
        "hashtag": "#Sens",
        "abbreviation": "OTT",
    },
    "PHI": {
        "name": "flyers",
        "handle": "@NHLFlyers",
        "hashtag": "#LetsGoFlyers",
        "abbreviation": "PHI",
    },
    "PIT": {
        "name": "penguins",
        "handle": "@penguins",
        "hashtag": "#LetsGoPens",
        "abbreviation": "PIT",
    },
    "SJS": {
        "name": "sharks",
        "handle": "@SanJoseSharks",
        "hashtag": "#SJSharks",
        "abbreviation": "SJS",
    },
    "STL": {
        "name": "blues",
        "handle": "@StLouisBlues",
        "hashtag": "#AllTogetherNowSTL",
        "abbreviation": "STL",
    },
    "TBL": {
        "name": "lightning",
        "handle": "@TBLightning",
        "hashtag": "#GoBolts",
        "abbreviation": "TBL",
    },
    "TOR": {
        "name": "mapleleafs",
        "handle": "@MapleLeafs",
        "hashtag": "#TMLTalk",
        "abbreviation": "TOR",
    },
    "VAN": {
        "name": "canucks",
        "handle": "@Canucks",
        "hashtag": "#Canucks",
        "abbreviation": "VAN",
    },
    "VGK": {
        "name": "goldenknights",
        "handle": "@GoldenKnights",
        "hashtag": "#VegasGoesGold",
        "abbreviation": "VGK",
    },
    "WSH": {
        "name": "capitals",
        "handle": "@Capitals",
        "hashtag": "#ALLCAPS",
        "abbreviation": "WSH",
    },
    "WPG": {
        "name": "jets",
        "handle": "@NHLJets",
        "hashtag": "#GoJetsGo",
        "abbreviation": "WPG",
    },
}
