teams = {
    "ducks": {
        "name": "ducks",
        "city": "Anaheim",
        "handle": "@AnaheimDucks",
        "hashtag": "#LetsGoDucks",
        "abbreviation": "ANA",
    },
    "coyotes": {
        "name": "coyotes",
        "city": "Arizona",
        "handle": "@ArizonaCoyotes",
        "hashtag": "#Yotes",
        "abbreviation": "ARI",
    },
    "bruins": {
        "name": "bruins",
        "city": "Boston",
        "handle": "@NHLBruins",
        "hashtag": "#NHLBruins",
        "abbreviation": "BOS",
    },
    "sabres": {
        "name": "sabres",
        "city": "Buffalo",
        "handle": "@BuffaloSabres",
        "hashtag": "#Sabres",
        "abbreviation": "BUF",
    },
    "flames": {
        "name": "flames",
        "city": "Calgary",
        "handle": "@NHLFlames",
        "hashtag": "#CofRed",
        "abbreviation": "CGY",
    },
    "hurricanes": {
        "name": "hurricanes",
        "city": "Carolina",
        "handle": "@NHLCanes",
        "hashtag": "#Redvolution",
        "abbreviation": "CAR",
    },
    "blackhawks": {
        "name": "blackhawks",
        "city": "Chicago",
        "handle": "@NHLBlackhawks",
        "hashtag": "#Blackhawks",
        "abbreviation": "CHI",
    },
    "avalanche": {
        "name": "avalanche",
        "city": "Colorado",
        "handle": "@Avalanche",
        "hashtag": "#GoAvsGo",
        "abbreviation": "COL",
    },
    "bluejackets": {
        "name": "bluejackets",
        "city": "Columbus",
        "handle": "@BlueJacketsNHL",
        "hashtag": "#CBJ",
        "abbreviation": "CBJ",
    },
    "stars": {
        "name": "stars",
        "city": "Dallas",
        "handle": "@DallasStars",
        "hashtag": "#GoStars",
        "abbreviation": "DAL",
    },
    "redwings": {
        "name": "redwings",
        "city": "Detroit",
        "handle": "@DetroitRedWings",
        "hashtag": "#LGRW",
        "abbreviation": "DET",
    },
    "oilers": {
        "name": "oilers",
        "city": "Edmonton",
        "handle": "@EdmontonOilers",
        "hashtag": "#LetsgoOilers",
        "abbreviation": "EDM",
    },
    "panthers": {
        "name": "panthers",
        "city": "Florida",
        "handle": "@FlaPanthers",
        "hashtag": "#FlaPanthers",
        "abbreviation": "FLA",
    },
    "kings": {
        "name": "kings",
        "city": "Los Angeles",
        "handle": "@LAKings",
        "hashtag": "#GoKingsGo",
        "abbreviation": "LAK",
    },
    "wild": {
        "name": "wild",
        "city": "Minnesota",
        "handle": "@mnwild",
        "hashtag": "#mnwild",
        "abbreviation": "MIN",
    },
    "canadiens": {
        "name": "canadiens",
        "city": "Montreal",
        "handle": "@CanadiensMTL",
        "hashtag": "#GoHabsGo",
        "abbreviation": "MTL",
    },
    "predators": {
        "name": "predators",
        "city": "Nashville",
        "handle": "@PredsNHL",
        "hashtag": "#Preds",
        "abbreviation": "NSH",
    },
    "devils": {
        "name": "devils",
        "city": "New Jersey",
        "handle": "@NJDevils",
        "hashtag": "#NJDevils",
        "abbreviation": "NJD",
    },
    "islanders": {
        "name": "islanders",
        "city": "New York",
        "handle": "@NYIslanders",
        "hashtag": "#Isles",
        "abbreviation": "NYI",
    },
    "rangers": {
        "name": "rangers",
        "city": "New York",
        "handle": "@NYRangers",
        "hashtag": "#NYR",
        "abbreviation": "NYR",
    },
    "senators": {
        "name": "senators",
        "city": "Ottawa",
        "handle": "@Senators",
        "hashtag": "#Sens",
        "abbreviation": "OTT",
    },
    "flyers": {
        "name": "flyers",
        "city": "Philadelphia",
        "handle": "@NHLFlyers",
        "hashtag": "#LetsGoFlyers",
        "abbreviation": "PHI",
    },
    "penguins": {
        "name": "penguins",
        "city": "Pittsburgh",
        "handle": "@penguins",
        "hashtag": "#LetsGoPens",
        "abbreviation": "PIT",
    },
    "sharks": {
        "name": "sharks",
        "city": "San Jose",
        "handle": "@SanJoseSharks",
        "hashtag": "#SJSharks",
        "abbreviation": "SJS",
    },
    "blues": {
        "name": "blues",
        "city": "St. Louis",
        "handle": "@StLouisBlues",
        "hashtag": "#AllTogetherNowSTL",
        "abbreviation": "STL",
    },
    "lightning": {
        "name": "lightning",
        "city": "Tampa Bay",
        "handle": "@TBLightning",
        "hashtag": "#GoBolts",
        "abbreviation": "TBL",
    },
    "mapleleafs": {
        "name": "mapleleafs",
        "city": "Toronto",
        "handle": "@MapleLeafs",
        "hashtag": "#TMLTalk",
        "abbreviation": "TOR",
    },
    "canucks": {
        "name": "canucks",
        "city": "Vancouver",
        "handle": "@Canucks",
        "hashtag": "#Canucks",
        "abbreviation": "VAN",
    },
    "goldenknights": {
        "name": "goldenknights",
        "city": "Vegas",
        "handle": "@GoldenKnights",
        "hashtag": "#VegasGoesGold",
        "abbreviation": "VGK",
    },
    "capitals": {
        "name": "capitals",
        "city": "Washington",
        "handle": "@Capitals",
        "hashtag": "#ALLCAPS",
        "abbreviation": "WSH",
    },
    "jets": {
        "name": "jets",
        "city": "Winnipeg",
        "handle": "@NHLJets",
        "hashtag": "#GoJetsGo",
        "abbreviation": "WPG",
    },
}
